version: 2
updates:
  # Maintain dependencies in our GitHub Workflows
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      actions:
        patterns:
          - '*'
    cooldown:
      default-days: 7
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      npm:
        patterns:
          - '*'
    cooldown:
      default-days: 7
